// Generated by Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef ALPHAEQT_SWIFT_H
#define ALPHAEQT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AppKit;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlphaEqt",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


/// The base class for rendering a math equation.
SWIFT_CLASS("_TtC8AlphaEqt9MTDisplay")
@interface MTDisplay : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Renders an accent glyph (e.g., ^, ~, ˙) above a base accentee.
/// Matches iOSMath <code>MTAccentDisplay</code> behavior.
/// Positioning (TeX Appendix G, Rule 12 + OpenType MATH table):
/// <ol>
///   <li>
///     The accent is placed at (skew, accentee.ascent - accentBaseHeight).
///   </li>
///   <li>
///     <code>skew</code> = accenteeAdjustment - accentAdjustment, aligning the
///     attachment points of accent and accentee per font metrics.
///   </li>
///   <li>
///     Wrapping the accentee in a display ensures it contributes to
///     the full ascent/descent of the compound display.
///   </li>
/// </ol>
SWIFT_CLASS("_TtC8AlphaEqt15MTAccentDisplay")
@interface MTAccentDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8AlphaEqt15MTCTLineDisplay")
@interface MTCTLineDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Renders a background‑colored box with optional border around inner content.
/// Used for <code>\colorbox{color}{content}</code> and <code>\fcolorbox{border}{fill}{content}</code>.
SWIFT_CLASS("_TtC8AlphaEqt17MTColorboxDisplay")
@interface MTColorboxDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Renders a fraction using TeX Appendix G rules.
/// Coordinate system (matching SwiftMath):
/// <code>position.y</code> is the mathematical baseline (y=0 axis).
/// The fraction bar is drawn at <code>position.y + linePosition</code>.
/// <code>numeratorUp</code> is the distance from the baseline to the numerator’s baseline.
/// <code>denominatorDown</code> is the distance from the baseline to the denominator’s baseline.
/// TeX positioning algorithm (from the typesetter’s <code>makeFraction</code>):
/// <ol>
///   <li>
///     Start with <code>numeratorShiftUp</code> / <code>denominatorShiftDown</code> from the MATH table.
///   </li>
///   <li>
///     Compute the actual clearance between the numerator’s bottom and the bar top:
///     <code>distanceFromNumeratorToBar = (numeratorUp - num.descent) - (linePosition + ruleThickness/2)</code>
///   </li>
///   <li>
///     If clearance < <code>numeratorGapMin</code>, increase <code>numeratorUp</code> to meet the minimum.
///   </li>
///   <li>
///     Same for denominator: <code>distanceFromDenominatorToBar = (linePosition - ruleThickness/2) - (den.ascent - denominatorDown)</code>
///   </li>
///   <li>
///     If clearance < <code>denominatorGapMin</code>, increase <code>denominatorDown</code> to meet the minimum.
///   </li>
///   <li>
///     <code>ascent = num.ascent + numeratorUp</code>
///   </li>
///   <li>
///     <code>descent = den.descent + denominatorDown</code>
///   </li>
///   <li>
///     <code>width = max(num.width, den.width)</code>
///   </li>
/// </ol>
SWIFT_CLASS("_TtC8AlphaEqt17MTFractionDisplay")
@interface MTFractionDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Stacked glyph display built from extendable assembly parts.
/// Used for stretchy radicals and delimiters when no single pre‑built
/// variant is tall enough.
SWIFT_CLASS("_TtC8AlphaEqt26MTGlyphConstructionDisplay")
@interface MTGlyphConstructionDisplay : MTDisplay
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Standalone glyph display for drawing a single glyph.
/// <code>shiftDown</code> centers the glyph on the math axis: <code>0.5*(ascent-descent) - axisHeight</code>.
/// <code>rawAscent</code>/<code>rawDescent</code> hold the glyph’s true bounding box.
/// The public <code>ascent</code>/<code>descent</code> are adjusted when <code>shiftDown</code> is set
/// so parents see visual (axis-centered) bounds.
SWIFT_CLASS("_TtC8AlphaEqt14MTGlyphDisplay")
@interface MTGlyphDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Renders a large operator (e.g., ∑, ∫, ∏) with limits above/below
/// in display style. Matches iOSMath <code>MTLargeOpLimitsDisplay</code> behavior.
/// Positioning:
/// <ul>
///   <li>
///     Nucleus centered horizontally at <code>self.position</code>
///   </li>
///   <li>
///     Upper limit: <code>self.position.y + nuc.ascent + upperLimitGap + upper.descent</code>
///   </li>
///   <li>
///     Lower limit: <code>self.position.y - nuc.descent - lowerLimitGap - lower.ascent</code>
///   </li>
/// </ul>
/// Reported dimensions include full extent of limits:
/// <ul>
///   <li>
///     <code>ascent = nuc.ascent + extraPadding + upper.ascent + upperGap + upper.descent</code>
///   </li>
///   <li>
///     <code>descent = nuc.descent + extraPadding + lowerGap + lower.ascent + lower.descent</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC8AlphaEqt22MTLargeOpLimitsDisplay")
@interface MTLargeOpLimitsDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8AlphaEqt17MTMathListDisplay")
@interface MTMathListDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Renders a radical (square root / nth root) using TeX Appendix G rules.
/// When the √ glyph is shorter than the required radicand height,
/// a diagonal connector line (slope ~5.67 from font metrics) extends
/// from the glyph body up to the horizontal rule bar, avoiding the
/// ugly vertical extender assembly.
/// Coordinate system:
/// <code>position</code> is the baseline origin of the radical.
/// The radical glyph is placed at <code>local (radicalShift, 0)</code>.
/// The radicand sits at <code>local (radicalShift + glyphWidth, 0)</code>.
/// The rule bar connects from glyph right edge across the radicand width.
/// Dimensions:
/// <ul>
///   <li>
///     Width: glyphWidth + extenderDeltaX (if slope‑extended) + radicand.width
///   </li>
///   <li>
///     Ascent: tops at ruleThickness + clearance + radicand.ascent + extraAscender
///   </li>
/// </ul>
SWIFT_CLASS("_TtC8AlphaEqt16MTRadicalDisplay")
@interface MTRadicalDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Draws a filled horizontal rule (rectangle) with configurable thickness.
/// Used for overbar accents (<code>\bar{abc}</code>) when the font lacks stretchy glyph variants.
/// Positioned such that the rule’s center is at y=0; the caller sets <code>position.y</code>
/// to place it correctly above the accentee.
/// Renders a filled horizontal rule (rectangle) with configurable thickness.
/// y=0 is the <em>bottom</em> edge of the rule (ascent = thickness, descent = 0),
/// matching glyph display semantics so the rule can be positioned using
/// the same <code>accentBaseHeight</code> formula as accent glyphs.
SWIFT_CLASS("_TtC8AlphaEqt13MTRuleDisplay")
@interface MTRuleDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8AlphaEqt15MTSupSubDisplay")
@interface MTSupSubDisplay : MTDisplay
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;

SWIFT_CLASS("_TtC8AlphaEqt8MathView")
@interface MathView : NSView
- (nonnull instancetype)initWithFrame:(NSRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) NSSize intrinsicContentSize;
- (void)drawRect:(NSRect)dirtyRect;
- (void)viewDidEndLiveResize;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
